name: Update Quiz
on:
  schedule:
    - cron: '0 * * * *' # Tourne toutes les heures
  workflow_dispatch:      # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-genai

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python process.py

      - name: Save changes to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # On ajoute tout (manifest et dossier data)
          git add .
          
          # On commit. Si pas de changement, on ne fait rien sans erreur.
          git commit -m "ðŸš€ Mise Ã  jour automatique des quiz" || exit 0
          
          # On pousse les changements
          git push
